/**
 * Swagger/OpenAPI 3.0 configuration.
 * Auto-generates API documentation from JSDoc annotations in route files.
 */

const swaggerJsdoc = require('swagger-jsdoc');
const config = require('../config');

const swaggerDefinition = {
  openapi: '3.0.0',
  info: {
    title: config.swagger.title,
    version: config.swagger.version,
    description: config.swagger.description,
    contact: {
      name: 'CoreSY API Support',
      email: 'support@coresy.io',
    },
    license: {
      name: 'MIT',
      url: 'https://opensource.org/licenses/MIT',
    },
  },
  servers: [
    {
      url: `https://coresy-backend-production.up.railway.app${config.apiPrefix}`,
      description: 'Production server (Railway)',
    },
    {
      url: `http://localhost:${config.port}${config.apiPrefix}`,
      description: 'Development server',
    },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'Enter your JWT token',
      },
    },
    schemas: {
      SuccessResponse: {
        type: 'object',
        properties: {
          success: { type: 'boolean', example: true },
          message: { type: 'string', example: 'Success' },
          data: { type: 'object' },
        },
      },
      ErrorResponse: {
        type: 'object',
        properties: {
          success: { type: 'boolean', example: false },
          message: { type: 'string', example: 'An error occurred' },
          errors: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                field: { type: 'string' },
                message: { type: 'string' },
              },
            },
          },
        },
      },
      HealthResponse: {
        type: 'object',
        properties: {
          success: { type: 'boolean', example: true },
          message: { type: 'string', example: 'CoreSY API is running' },
          data: {
            type: 'object',
            properties: {
              status: { type: 'string', example: 'healthy' },
              timestamp: { type: 'string', format: 'date-time' },
              uptime: { type: 'number', example: 123.456 },
              environment: { type: 'string', example: 'development' },
            },
          },
        },
      },
      Governorate: {
        type: 'object',
        properties: {
          id: { type: 'string', example: 'static-aleppo' },
          name: { type: 'string', example: 'Aleppo' },
          nameAr: { type: 'string', example: 'حلب' },
          code: { type: 'string', example: 'AL' },
        },
      },
      User: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          passId: { type: 'string', example: 'AL-000001' },
          fullName: { type: 'string', example: 'Ahmad Al-Hassan' },
          email: { type: 'string', example: 'ahmad@example.com' },
          phoneNumber: { type: 'string', example: '+963912345678' },
          status: { type: 'string', example: 'PENDING_VERIFICATION' },
        },
      },
      LoginRequest: {
        type: 'object',
        required: ['identifier', 'password'],
        properties: {
          identifier: { type: 'string', example: 'ahmad@example.com' },
          password: { type: 'string', example: 'SecurePass1!' },
        },
      },
      RegisterRequest: {
        type: 'object',
        required: [
          'fullName',
          'email',
          'phoneNumber',
          'password',
          'confirmPassword',
          'governorateId',
          'acceptTerms',
        ],
        properties: {
          fullName: { type: 'string', example: 'Ahmad Al-Hassan' },
          email: { type: 'string', example: 'ahmad@example.com' },
          phoneNumber: { type: 'string', example: '+963912345678' },
          smartAssistantName: { type: 'string', example: 'CoreAssist' },
          password: { type: 'string', example: 'SecurePass1!' },
          confirmPassword: { type: 'string', example: 'SecurePass1!' },
          governorateId: { type: 'string', example: 'static-aleppo' },
          acceptTerms: { type: 'boolean', example: true },
        },
      },
      AuthResponse: {
        type: 'object',
        properties: {
          accessToken: { type: 'string' },
          refreshToken: { type: 'string' },
          expiresIn: { type: 'string', example: '7d' },
          user: { $ref: '#/components/schemas/User' },
        },
      },
      Role: {
        type: 'object',
        required: ['name', 'displayName'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string', example: 'CUSTOM_ROLE' },
          displayName: { type: 'string', example: 'Custom Role' },
          description: { type: 'string', example: 'Role description' },
          priority: { type: 'integer', example: 50 },
          isSystem: { type: 'boolean', example: false },
          status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'], example: 'ACTIVE' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Permission: {
        type: 'object',
        required: ['module', 'name', 'slug'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          module: { type: 'string', example: 'Users' },
          name: { type: 'string', example: 'Create User' },
          slug: { type: 'string', example: 'users.create' },
          description: { type: 'string', example: 'Create new users' },
          status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'], example: 'ACTIVE' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Admin: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          passId: { type: 'string', example: 'AL-000001' },
          fullName: { type: 'string', example: 'John Doe' },
          email: { type: 'string', example: 'admin@example.com' },
          phoneNumber: { type: 'string', example: '+963912345678' },
          profileImage: { type: 'string', example: 'https://example.com/profile.jpg' },
          role: { $ref: '#/components/schemas/Role' },
          status: {
            type: 'string',
            enum: ['PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED'],
            example: 'ACTIVE',
          },
          lastLogin: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Business: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string', example: 'Business Name' },
          type: { type: 'string', example: 'RESTAURANT' },
          category: { type: 'string', example: 'Food & Beverage' },
          description: { type: 'string', example: 'Business description' },
          ownerName: { type: 'string', example: 'Owner Name' },
          ownerEmail: { type: 'string', example: 'owner@example.com' },
          ownerPhone: { type: 'string', example: '+963912345678' },
          businessEmail: { type: 'string', example: 'business@example.com' },
          businessPhone: { type: 'string', example: '+963987654321' },
          registrationNumber: { type: 'string', example: '123456789' },
          taxNumber: { type: 'string', example: '987654321' },
          website: { type: 'string', example: 'https://example.com' },
          governorate: { $ref: '#/components/schemas/Governorate' },
          city: { type: 'string', example: 'Damascus' },
          address: { type: 'string', example: 'Main Street, 123' },
          latitude: { type: 'number', example: 33.5138 },
          longitude: { type: 'number', example: 36.2765 },
          status: { type: 'string', example: 'PENDING' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Branch: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string', example: 'Main Branch' },
          code: { type: 'string', example: 'REST-001' },
          businessId: { type: 'string', format: 'uuid' },
          business: { $ref: '#/components/schemas/Business' },
          type: { type: 'string', example: 'Restaurant' },
          description: { type: 'string', example: 'Branch description' },
          governorate: { $ref: '#/components/schemas/Governorate' },
          city: { type: 'string', example: 'Damascus' },
          address: { type: 'string', example: 'Main Street, 456' },
          latitude: { type: 'number', example: 33.514 },
          longitude: { type: 'number', example: 36.277 },
          googleMapLink: { type: 'string', example: 'https://maps.google.com' },
          contactEmail: { type: 'string', example: 'branch@example.com' },
          contactPhone: { type: 'string', example: '+963987654321' },
          whatsAppNumber: { type: 'string', example: '+963987654321' },
          workingDays: { type: 'array', items: { type: 'string' } },
          openingTime: { type: 'string', example: '09:00' },
          closingTime: { type: 'string', example: '21:00' },
          emergencyContact: { type: 'string', example: '+963912345678' },
          image: { type: 'string', example: 'https://example.com/branch.jpg' },
          coverImage: { type: 'string', example: 'https://example.com/cover.jpg' },
          status: { type: 'string', example: 'PENDING' },
          isMain: { type: 'boolean', example: false },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Service: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string', example: 'Breakfast Special' },
          code: { type: 'string', example: 'REST-0001' },
          businessId: { type: 'string', format: 'uuid' },
          business: { $ref: '#/components/schemas/Business' },
          branchId: { type: 'string', format: 'uuid' },
          branch: { $ref: '#/components/schemas/Branch' },
          category: { type: 'string', example: 'FOOD_AND_DRINKS' },
          type: { type: 'string', example: 'RESTAURANT' },
          description: { type: 'string', example: 'Delicious breakfast with coffee and pastries' },
          shortDescription: { type: 'string', example: 'Coffee & pastries' },
          price: { type: 'number', example: 25.99 },
          discountPercentage: { type: 'number', example: 10 },
          coresyDiscount: { type: 'number', example: 5 },
          platformFee: { type: 'number', example: 1.5 },
          duration: { type: 'integer', example: 30 },
          maxCapacity: { type: 'integer', example: 20 },
          bookingRequired: { type: 'boolean', example: false },
          appointmentRequired: { type: 'boolean', example: false },
          deliveryAvailable: { type: 'boolean', example: false },
          isFeatured: { type: 'boolean', example: true },
          serviceImage: { type: 'string', example: 'https://example.com/service.jpg' },
          galleryImages: { type: 'array', items: { type: 'string' } },
          status: { type: 'string', example: 'DRAFT' },
          createdBy: { type: 'string', format: 'uuid' },
          updatedBy: { type: 'string', format: 'uuid' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Cashier: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          fullName: { type: 'string', example: 'Mohammad Ali' },
          employeeId: { type: 'string', example: 'CSH-000001' },
          email: { type: 'string', example: 'mohammad@example.com' },
          phoneNumber: { type: 'string', example: '+963912345678' },
          businessId: { type: 'string', format: 'uuid' },
          business: { $ref: '#/components/schemas/Business' },
          branchId: { type: 'string', format: 'uuid' },
          branch: { $ref: '#/components/schemas/Branch' },
          profileImage: { type: 'string', example: 'https://example.com/cashier.jpg' },
          status: {
            type: 'string',
            enum: ['PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'RESIGNED', 'DELETED'],
            example: 'ACTIVE',
          },
          joiningDate: { type: 'string', format: 'date-time' },
          lastLogin: { type: 'string', format: 'date-time' },
          createdBy: { type: 'string', format: 'uuid' },
          updatedBy: { type: 'string', format: 'uuid' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Slot: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          serviceId: { type: 'string', format: 'uuid' },
          service: { $ref: '#/components/schemas/Service' },
          businessId: { type: 'string', format: 'uuid' },
          business: { $ref: '#/components/schemas/Business' },
          branchId: { type: 'string', format: 'uuid' },
          branch: { $ref: '#/components/schemas/Branch' },
          slotDate: { type: 'string', format: 'date-time' },
          dayOfWeek: { type: 'integer', example: 1 },
          startTime: { type: 'string', example: '09:00' },
          endTime: { type: 'string', example: '10:00' },
          duration: { type: 'integer', example: 60 },
          maxCapacity: { type: 'integer', example: 20 },
          remainingCapacity: { type: 'integer', example: 20 },
          bookingType: { type: 'string', enum: ['RESERVATION', 'APPOINTMENT', 'WALK_IN'] },
          genderRestriction: { type: 'string', enum: ['MALE', 'FEMALE', 'BOTH'] },
          minAge: { type: 'integer', example: 18 },
          maxAge: { type: 'integer', example: 65 },
          isRecurring: { type: 'boolean', example: false },
          recurringType: { type: 'string', enum: ['DAILY', 'WEEKLY', 'MONTHLY', 'NONE'] },
          status: {
            type: 'string',
            enum: ['AVAILABLE', 'FULL', 'CLOSED', 'CANCELLED', 'INACTIVE'],
          },
          createdBy: { type: 'string', format: 'uuid' },
          updatedBy: { type: 'string', format: 'uuid' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      Booking: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          bookingNumber: { type: 'string', example: 'BK1234567890' },
          customerId: { type: 'string', format: 'uuid' },
          customer: { $ref: '#/components/schemas/User' },
          businessId: { type: 'string', format: 'uuid' },
          business: { $ref: '#/components/schemas/Business' },
          branchId: { type: 'string', format: 'uuid' },
          branch: { $ref: '#/components/schemas/Branch' },
          serviceId: { type: 'string', format: 'uuid' },
          service: { $ref: '#/components/schemas/Service' },
          slotId: { type: 'string', format: 'uuid' },
          slot: { $ref: '#/components/schemas/Slot' },
          bookingType: { type: 'string', enum: ['RESERVATION', 'APPOINTMENT', 'WALK_IN'] },
          reservationDate: { type: 'string', format: 'date-time' },
          startTime: { type: 'string', example: '09:00' },
          endTime: { type: 'string', example: '10:00' },
          numberOfGuests: { type: 'integer', example: 2 },
          specialInstructions: { type: 'string', example: 'Window seat preferred' },
          bookingSource: { type: 'string', enum: ['MOBILE_APP', 'WEB', 'WALK_IN', 'ADMIN'] },
          paymentMethod: { type: 'string', example: 'Credit Card' },
          paymentStatus: {
            type: 'string',
            enum: ['PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CASH', 'WALLET'],
          },
          status: {
            type: 'string',
            enum: [
              'PENDING',
              'CONFIRMED',
              'CHECKED_IN',
              'IN_PROGRESS',
              'COMPLETED',
              'CANCELLED',
              'EXPIRED',
              'REJECTED',
              'NO_SHOW',
            ],
          },
          qrCode: { type: 'string' },
          checkInTime: { type: 'string', format: 'date-time' },
          checkOutTime: { type: 'string', format: 'date-time' },
          cancellationReason: { type: 'string' },
          createdBy: { type: 'string', format: 'uuid' },
          updatedBy: { type: 'string', format: 'uuid' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
    },
  },
  tags: [
    { name: 'Health', description: 'Health check endpoints' },
    { name: 'Debug', description: 'Debug and diagnostic endpoints' },
    { name: 'Governorates', description: 'Syrian governorates endpoints' },
    { name: 'Auth', description: 'Authentication endpoints' },
    { name: 'Roles', description: 'Role management endpoints' },
    { name: 'Permissions', description: 'Permission management endpoints' },
    { name: 'User Roles', description: 'User role assignment endpoints' },
    { name: 'Users', description: 'User management endpoints' },
    { name: 'Admins', description: 'Admin management endpoints' },
    { name: 'Businesses', description: 'Business management endpoints' },
    { name: 'Branches', description: 'Branch management endpoints' },
    { name: 'Services', description: 'Business service management endpoints' },
    { name: 'Cashiers', description: 'Cashier management endpoints' },
    { name: 'Slots', description: 'Slot management endpoints' },
    { name: 'Bookings', description: 'Booking management endpoints' },
  ],
};

const options = {
  swaggerDefinition,
  apis: [
    './src/routes/**/*.js',
    './src/docs/**/*.js',
    './src/modules/rbac/routes/**/*.js',
    './src/modules/admin/routes/**/*.js',
    './src/modules/business/routes/**/*.js',
    './src/modules/branch/routes/**/*.js',
    './src/modules/service/routes/**/*.js',
    './src/modules/cashier/routes/**/*.js',
    './src/modules/slot/routes/**/*.js',
    './src/modules/booking/routes/**/*.js',
  ],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
